### ISSUE TITLE
Example doesn't compile

### ISSUE THREAD

**Issue by evanmays** [jamsocket/stateroom#7]
```
git clone https://github.com/drifting-in-space/stateroom.git
cd stateroom
cd examples
cd native-echo
cargo check
```
the cargo check command line output https://app.warp.dev/block/IZrKz6eqSmHFYpjeeJb0TI

**Comment by paulgb** [comment]
Thanks Evan. Looks like maybe an update to Actix broke it, I’ll have a look this week.
